### PR TITLE
Refactor to use nan

### PR DESCRIPTION
**Pull request by achingbrain**
I've refactored posix.cc to use [nan](https://github.com/rvagg/nan) as the v8 API has changed quite a bit in node 0.12.

The code now compiles and all tests pass (as non-privileged and super user) on node 0.8, 0.10, 0.12 and io.js 1.1.0.

nan doesn't support node 0.6 so I've removed this from the package.json and travis.yml files.

The only thing I couldn't translate cleanly was:

```cc
return ThrowException(ErrnoException(errno, "chroot: chdir: "));
```

From [the docs](https://github.com/rvagg/nan#api_nan_throw_error) it looks like you should be able to use:

```cc
return NanThrowError("chroot: chdir: ", errno);
```

..but that ends up with the JavaScript error property `code` being an int instead of a string (e.g. `2` vs `ENOENT`) which is less useful so I left it as the node `ErrnoException` call.  I'll open an issue with nan to try to get some clarity.

The only other thing was that in test-setsid.js writing anything to stdout after the first successful setsid call caused the test to fail on node 0.12 and io.js.  I removed that line and the test passes.  This would ordinarily ring alarm bells, but is exposing setsid actually necessary?  Unless I've missed something you can achieve a similar effect (e.g. detaching a process from it's parent and letting it continue) by unRef()ing a child_process.

### CODE REVIEW

**Comment by melor** [comment]
This looks great! I will read this more carefully soon and merge it + bump to a new major version if everything looks ok.

**Comment by achingbrain** [comment]
Weird, looks like Travis is having some [problems](https://travis-ci.org/melor/node-posix/jobs/50318752)  with nvm:

```sh
$ nvm install iojs-v1.1.0
/Users/travis/build.sh: line 41: nvm: command not found
The command "nvm install iojs-v1.1.0" failed and exited with 127 during .
Your build has been stopped.
```

**Comment by melor** [comment]
@achingbrain that's on OSX. I just got the Travis OSX beta support activated for this repo and apparently it does not work out of the box. I'll either fix or disable it, don't worry about it...

**Comment by achingbrain** [comment]
Great.  FWIW there's this: travis-ci/travis-ci#2311 So yeah, nvm is not there yet.

Looks like some people even [add it manually](https://github.com/nodegit/nodegit/blob/master/.travis.yml#L4-L8).  Yikes.

**Comment by melor** [comment]
@achingbrain v2.0.0 available at the usual locations. Thank you very much!

**Pull request merged**
